#!/bin/bash

        if [ -f ~/.bash_profile ]; then
            source ~/.bash_profile
            if [ ! -z "${?:resource/UCDSIC_GOLDENGATE_SETDB}" ]; then 
                #Executando SETDB
                #setdb ${?:resource/UCDSIC_GOLDENGATE_SETDB}
                . /oracle/tools/profile_db.sh ${?:resource/UCDSIC_GOLDENGATE_SETDB}
                echo "DEBUG:        Sistema Operacional Linux";
            fi
        elif [ -f ~/.profile ]; then
            . ~/.profile
            echo "DEBUG:        Sistema Operacional AIX";
        else 
            echo "Plataforma não identificada - Não é AIX - Não é Linux";
            exit 1;
        
        fi
        
        echo "DEBUG:        ORACLE_HOME= "$ORACLE_HOME;
        echo "DEBUG:        ORACLE_SID= "$ORACLE_SID
        echo "DEBUG:        LD_LIBRARY_PATH= "$LD_LIBRARY_PATH;
        echo "DEBUG:        LIBPATH= "$LIBPATH;
    
        
cd  ${p:resource/UCDSIC_GOLDENGATE_HOME}

echo "defsfile ${p:resource/UCDSIC_GOLDENGATE_HOME}/dirdef/defgen_${p:component.name}_${p:application.name}.def purge format release 12.1" > ${p:resource/UCDSIC_GOLDENGATE_HOME}/dirdef/create_defgen_${p:component.name}_${p:application.name}.gen

    if [ -f ${p:resource/UCDSIC_GOLDENGATE_HOME}/dirprm/${p:resource/UCDSIC_GOLDENGATE_PARAM_NOME_EXTRATOR} ]; then
        DBLOGIN=`cat ${p:resource/UCDSIC_GOLDENGATE_HOME}/dirprm/${p:resource/UCDSIC_GOLDENGATE_PARAM_NOME_EXTRATOR} |grep -i userid |grep -v "\-\-"`;
        DBLOGIN_PDB=`echo $DBLOGIN|grep -i userid|grep -i c##`;
        
        if [ ! -z "$DBLOGIN_PDB" ]; then 
            echo "--------------- BANCO Pluglable ---------------"
            echo "Procurando no PRM o parametro SOURCECATALOG"    
            
            SOURCECATALOG=`cat ${p:resource/UCDSIC_GOLDENGATE_HOME}/dirprm/${p:resource/UCDSIC_GOLDENGATE_PARAM_NOME_EXTRATOR} |grep -i "SOURCECATALOG"|awk {' print $2'}`;
            #if [ ! -z "$SOURCECATALOG" ]; then
            #    DBLOGIN=`echo $DBLOGIN|sed s/ggate/ggate@$SOURCECATALOG/g`;
            #fi
            if [ ! -z "$SOURCECATALOG" ]; then
                ################################################################################
                ##########   Corrigir bug de arquivo sourcecatalog Plugable Database  ########## 
                SOURCECATALOG_TOTAL=`echo $SOURCECATALOG|wc -w`;
                
                echo;echo;echo;
                echo "Numero de catalogos identificados no extrator= "$SOURCECATALOG_TOTAL "SOURCECATALOG= "$SOURCECATALOG
                echo;echo;echo;
                
                 if [ "$SOURCECATALOG_TOTAL" -gt "1" ]; then
                   ##########   Tem DOIS SOURCECATALOG no Extrator   ########## 
                    SOURCECATALOG_2=`echo ${p:component.name}|awk -F"-" {' print $3 '}`
                    DBLOGIN=`echo $DBLOGIN|sed s/ggate/ggate@$SOURCECATALOG_2/g`;
                 else 
                    DBLOGIN=`echo $DBLOGIN|sed s/ggate/ggate@$SOURCECATALOG/g`;
                 fi 
                ################################################################################
            fi
        fi
        
        if [ -z "$DBLOGIN" ]; then
                echo "Não foi possivel encontrar DBLOGIN no extrator"
                exit 1;
        else
            #Heartbeat é obrigatório.
            echo $DBLOGIN  >> ${p:resource/UCDSIC_GOLDENGATE_HOME}/dirdef/create_defgen_${p:component.name}_${p:application.name}.gen
            echo "TABLE GGATE.HEARTBEAT;" >> ${p:resource/UCDSIC_GOLDENGATE_HOME}/dirdef/create_defgen_${p:component.name}_${p:application.name}.gen
            echo "TABLE C##GGATE.HEARTBEAT;" >> ${p:resource/UCDSIC_GOLDENGATE_HOME}/dirdef/create_defgen_${p:component.name}_${p:application.name}.gen
            
            cat ${p:resource/UCDSIC_GOLDENGATE_HOME}/dirmac/lista_tabelas_${p:component.name}_${p:application.name}.inc|sed -e "s/\^M//"|grep -v "\-\-"|grep -i table|awk {' print $1" "$2";" '}|sed s/,//g >> ${p:resource/UCDSIC_GOLDENGATE_HOME}/dirdef/create_defgen_${p:component.name}_${p:application.name}.gen
            
           # cd ${p:resource/UCDSIC_GOLDENGATE_HOME}
            
            ${p:resource/UCDSIC_GOLDENGATE_HOME}/./defgen paramfile ${p:resource/UCDSIC_GOLDENGATE_HOME}/dirdef/create_defgen_${p:component.name}_${p:application.name}.gen
                  if [ $? != 0 ]; then
                      echo ; echo ;
                      echo "---->> Erro ao executar o DEFGEN"; echo ; echo ;
                      exit 1 ;
                  fi
            rm ${p:resource/UCDSIC_GOLDENGATE_HOME}/dirdef/create_defgen_${p:component.name}_${p:application.name}.gen
            
        fi
    else
        echo "Correção bug PRM inexistente - 17-Abril-2018"
        echo "PRM ${p:resource/UCDSIC_GOLDENGATE_HOME}/dirprm/${p:resource/UCDSIC_GOLDENGATE_PARAM_NOME_EXTRATOR} não encontrado"
        echo "RESOLUÇÃO - Verificar variavel udeploy UCDSIC_GOLDENGATE_PARAM_NOME_EXTRATOR ou UCDSIC_GOLDENGATE_HOME "
        exit 1;
    fi
